import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-400 text-gray-900 min-h-screen flex items-start justify-center p-4`}
      >
        <div className="w-full max-w-lg sm:max-w-xl p-6 bg-white rounded-lg shadow-lg mt-8 mx-auto">
          {/* Inner box with content */}
          <div className="w-full p-6 bg-white rounded-lg shadow-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
